# Generated by Django 6.0.5 on 2026-05-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referred_by_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
